<?php
/**
 * @file
 * Functions to support theming in the Kallehauge theme.
 */

/**
 * Implements hook_page_attachments_alter().
 *
 * Add "admin library" if the user is logged in. We do this to avoid loading
 * styling and JavaScript when it isn't needed.
 */
function kallehauge_page_attachments_alter(array &$attachments) {
  // If the user is logged in.
  if (\Drupal::currentUser()->isAuthenticated()) {
    $attachments['#attached']['library'][] = 'kallehauge/admin-styling';
  }
}
